# python base image in the container from Docker Hub
FROM python:3.8.12

# copy files to the /app folder in the container
COPY requirements.txt /app/requirements.txt
COPY api.py /app/api.py
COPY notebooks/supervised.pkl /app/notebooks/supervised.pkl

WORKDIR /app

RUN pip install -r requirements.txt

# execute the command python main.py (in the WORKDIR) to start the app
CMD uvicorn api:app --host 0.0.0.0 --port $PORT
